### ISSUE TITLE
Open Trade Should be Searchable by Name

### ISSUE THREAD

**Issue by ajazRahman** [sarmaayapk/androidapp#1]
Currently the Open trade open is only searchable by Script id, it should be searchable by name of the company, which is not intutive.

Also when the script is selected, show the name of the company below the script so that there are no mistakes.

**Comment by babarsiddique** [comment]
Completed - Now the trades are Searchable by their names and codes. 
In Open Trade and watchlist fragments that search feature is added.
When Symbol or script is selected Full Name is shown in the StockName Bar.

**Comment by babarsiddique** [comment]
![Screenshot_20200819-110829](https://user-images.githubusercontent.com/37567340/90598460-86f66100-e20c-11ea-9986-8495863c07da.png)
